- app/src/main/AndroidManifest.xml
- app/src/main/java/fr/paug/androidmakers/manager/AgendaRepository.java
- app/src/main/java/fr/paug/androidmakers/service/SessionAlarmService.java
- app/src/main/java/fr/paug/androidmakers/ui/activity/DetailActivity.java
- app/src/main/java/fr/paug/androidmakers/ui/fragment/AgendaFragment.java
Show the room on the notifications
Allow multiple notifications if there are several starred sessions that begins at the same time.
Remove the alarm when a session is unstarred.
When the data source is updated, recreate all alarms in case the schedule has changed.
Fixed a bug where we cannot fetch the session or the slot information because the AgendaRepository was not ready.
> [DEV] Reworked notifications for starred sessions

- app/src/main/AndroidManifest.xml
- app/src/main/java/fr/paug/androidmakers/receiver/SessionAlarmReceiver.java
- app/src/main/java/fr/paug/androidmakers/service/SessionAlarmService.java
- app/src/main/java/fr/paug/androidmakers/ui/fragment/AgendaFragment.java
- app/src/main/java/fr/paug/androidmakers/util/ScheduleSessionHelper.java
SessionAlarmService currently crashes after Oreo devices boot because background services may not be started when the app is not in the foreground.
The proper fix is to reimplement SessionAlarmService as a JobIntentService which is a remplacement for IntentService.
AlarmManager intents are now also routed through the BroadcastReceiver so the job can be properly configured and launched.
Additionally, this pull request also uses AlarmManager.setExact() for more accurate notifications on API 19+ devices.
> SessionAlarmService fix for Android Oreo

- app/src/main/java/fr/paug/androidmakers/service/SessionAlarmService.java
Better default options are provided for the alarm notifications. The default options also need to be specified for the notification channel, because the display options of the notification itself are ignored on Android O and more recent: the notification channel options are used instead.
> Improved session alarm notifications

- app/src/main/java/fr/paug/androidmakers/ui/activity/BaseActivity.kt
- app/src/main/java/fr/paug/androidmakers/util/ScheduleSessionHelper.kt
ScheduleSessionHelper is a singleton that keeps a reference to the latest toast it showed. The toast has a reference to the context, that context can be a destroyed activity.
To reproduce: add LeakCanary, go to a session, add the session (toast shows), press back, press home.
Fix: when an activity, cancel any displayed toast.
> Fix toast leak

- app/src/main/java/fr/paug/androidmakers/ui/fragment/AgendaFragment.kt
- app/src/main/res/values/ids.xml
See https://github.com/paug/AndroidMakersApp/pull/59 for context.
Replacing the listener callback with onOptionsItemSelected makes the leak of the listener go away, even though the menu item itself is still leaking.
> Fix Options Menu leak in AgendaFragment

- app/build.gradle
- app/src/main/java/fr/paug/androidmakers/manager/AndroidMakersStore.kt
convert from the website data directly in the app. This way, slight changes to the schedule won't require any manual intervention to work on the app automagically
PS: I had to enable multidex to work on non-minified (debug) versions of the app. I'm okay to remove it if needed.
> Use schedule as single source of truth

- app/src/main/java/fr/paug/androidmakers/manager/AndroidMakersStore.kt
- app/src/main/java/fr/paug/androidmakers/ui/fragment/AboutFragment.kt
If you leave the AboutFragment before the partners request completes, it tries to inflate a view with a null context
> Fix a crash that could happen in the AboutFragment

- app/src/main/java/fr/paug/androidmakers/ui/components/AgendaLayout.kt
- app/src/main/java/fr/paug/androidmakers/ui/components/AgendaPager.kt
- store/src/commonMain/kotlin/fr/androidmakers/store/AndroidMakersStore.kt
> Fix some typos and indention

- app/src/main/java/fr/paug/androidmakers/ui/adapter/DaySchedule.kt
- app/src/main/java/fr/paug/androidmakers/ui/components/AgendaLayout.kt
- app/src/main/java/fr/paug/androidmakers/ui/components/AgendaPager.kt
> Set initialTab based on current date.

- app/src/main/java/fr/paug/androidmakers/ui/components/SessionDetailLayout.kt
- app/src/main/java/fr/paug/androidmakers/ui/components/VenueLayout.kt
- app/src/main/java/fr/paug/androidmakers/ui/util/TextUtil.kt
Closes https://github.com/paug/AndroidMakersApp/issues/101. 
I haven't found a way to display Html data in a composable just yet and TBH I kind of like that it's not too cluttered
> Discard HTML information

- app/src/main/java/fr/paug/androidmakers/ui/components/AgendaPager.kt
- app/src/main/java/fr/paug/androidmakers/ui/components/LceLayout.kt
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
This PR is trying to fix issue #116 
now the filter works like this
https://user-images.githubusercontent.com/14819756/164748797-7a756b97-48cb-4c5a-89fe-7f5744615b05.mp4
> fix filters rules

- app/build.gradle.kts
- app/src/main/java/fr/paug/androidmakers/ui/components/AgendaLayout.kt
- app/src/main/java/fr/paug/androidmakers/ui/components/AgendaLayoutViewModel.kt
- app/src/main/java/fr/paug/androidmakers/ui/components/AgendaPager.kt
- app/src/main/java/fr/paug/androidmakers/util/SessionFilter.kt
- app/src/test/java/fr/paug/androidmakers/fixtures/FakeAndroidMakersStore.kt
- app/src/test/java/fr/paug/androidmakers/ui/components/AgendaLayoutViewModelTest.kt
I used rememberSaveable rather than remember in order to preserve the filters across recreations.
Also to be able to save the `SessionFilter`, I noticed that `value` is always a `String`, so I thought it would be appropriate to convert to String in order to make it fully Parcelable. If we wanted to have a more extensible solution for the future, perhaps we could adopt a sealed class approach, where each subtype is a `FilterType`. however, I thought that might be overkill, and let's settle for a simpler approach that does the job decent enough. 
Fixes #121
> Fix filters resetting when returning from session details

- app/src/main/java/fr/paug/androidmakers/ui/components/agenda/AgendaColumn.kt
- app/src/main/java/fr/paug/androidmakers/ui/components/agenda/AgendaRow.kt
This makes only the text clickable to avoid clicking by mistake by adding a favorite
Also uses a different background for service sessions vs actual sessions
See #158
See #157
https://user-images.githubusercontent.com/3974977/234314471-9a0d6866-1cb1-443a-8532-caae74f62690.mp4
> Rework a bit the ListItem clickable UX

- app/src/main/java/fr/paug/androidmakers/ui/MainActivity.kt
We're not really planning on sending notifications so might as well not put this popup at first launch. Should revisit if we add notifications for bookmarks/upcoming talks
> Disable the notification popup

- app/src/main/java/fr/paug/androidmakers/ui/components/speakers/SpeakerScreen.kt
When the speaker has no "company", the alignment of the name was incorrect.
I don't know if the absence of company is an issue or a feature, though 🧐
> Small adjustment on Speaker title alignment

- wearApp/src/main/res/values/styles.xml
Forces the wear app splash screen to always display the icon.
Avoid the app from being rejected because of the "Missing app icon in splash screen" issue.
[Splash screen API](https://developer.android.com/develop/ui/views/launch/splash-screen#set-theme)
[Wear guidelines](https://developer.android.com/design/ui/wear/guides/behaviors-and-patterns/launch#branded)
> Forces the wear app splash screen to always display the icon.

- shared/data/src/androidMain/kotlin/fr/androidmakers/store/graphql/ApolloClientBuilder.android.kt
- shared/data/src/commonMain/graphql/operations.graphql
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/mappers.kt
- shared/di/src/androidMain/kotlin/fr/androidmakers/di/DataModule.android.kt
- shared/di/src/iosMain/kotlin/fr/androidmakers/di/DataModule.ios.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaUtils.kt
Not 100% perfect yet but at least we'll test using real data. Still missing:
* isServiceSession
* Authentified calls are not working
* Venue
If you want to test OpenFeedback, you'll have to set your device Clock in the future 👽 
Next steps:
* switching the endpoint to our own instance of Confetti so that we can authentify with our own firebase project. 
* fix isServiceSession and Venue calls
* add OpenFeedback debug setting to avoid changing the device clock
> Use 2024 data

- wearApp/src/main/java/fr/paug/androidmakers/wear/di/ViewModelModule.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/common/Loading.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/main/MainActivity.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/main/MainViewModel.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/main/Navigation.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/session/PreviewData.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/session/UISession.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/session/details/SessionDetailScreen.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/session/details/SessionDetailViewModel.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/signin/SignInScreen.kt
[sessiondetail.webm](https://github.com/paug/AndroidMakersApp/assets/372852/45704a2b-c785-43fa-b53a-21692ff57c07)
> Wear app: Add session detail screen

- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/common/PulsatingRedDot.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/session/UISession.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/session/details/SessionDetailScreen.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/session/list/SessionListScreen.kt
- wearApp/src/main/res/values/styles.xml
- Sessions that are over are grayed out
- Sessions that are ongoing have a red blinking dot
- Automatically scroll to the next not over session in the list
In this example I've set the watch to the 25th of April, at 14h15:
[scroll.webm](https://github.com/paug/AndroidMakersApp/assets/372852/f79f70e7-c778-4aed-9d33-f8a1a154905a)
> Wear app: Scroll to next session

- shared/data/build.gradle.kts
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/SpeakersGraphQLRepository.kt
It was fetched from the cache first
> Fetch speaker list from the network

- CONTRIBUTING.md
- shared/data/build.gradle.kts
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/mappers.kt
- shared/di/src/androidMain/kotlin/fr/androidmakers/di/DataModule.android.kt
- shared/di/src/iosMain/kotlin/fr/androidmakers/di/DataModule.ios.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/model/Venue.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/venue/VenuePager.kt
This is so that we can have our own bookmarks and Google Signin
> Use androidmakers.fr API

- shared/di/src/commonMain/kotlin/fr/androidmakers/di/DomainModule.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/interactor/ApplyForAppClinicUseCase.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/model/AppClinic.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/di/ViewModelModule.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaColumn.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaPager.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaPagerViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaRow.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaUtils.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/SessionDetailLayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/SessionDetailViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/model/uimodel.kt
- shared/ui/src/commonMain/moko-resources/base/strings.xml
- shared/ui/src/commonMain/moko-resources/fr/strings.xml
Adds a button on the agenda pager and on the App-Clinic's session details to apply for the App-Clinic as a candidate app.
The button triggers a mailto URL opening. The URL contains pre-redacted email content.
Here is the pre-redacted content:
* receiver : app.clinic@paug.fr
* subject: App-Clinic - [YOUR_APP]
* body: 
```
Hi Android Makers,
I'm interested in participating in the App-Clinic. Below are the details of my app:
Name:
Short Description:
Company:
Store URL (or link to an APK file):
Requirements:
Anything Else?:
Best,
[Your Name]
```
Provides an easy way to apply for the App-Clinic.
resolves #208 
Tested on Android with an email client app on the device.
⚠️ Needs testing on iOS⚠️
[Screen_recording_20240409_151906.webm](https://github.com/paug/AndroidMakersApp/assets/10415655/7bc684 …
> 📣 Adds a button to apply for the App-Clinic.

- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/session/list/SessionListScreen.kt
Same as the phone app, the service sessions have a darker background:
[dark-service-sessions.webm](https://github.com/paug/AndroidMakersApp/assets/372852/375f86b3-df08-461e-9257-1a8c5422f2fc)
> [Wear app] Distinguish service sessions with a different background

- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/venue/FloorPlan.kt
When switching from Afterparty tab to the Floor Plan tab, a small space at the top of the map and quickly disappear after.
Clearly specifying size modifiers of the `Box` fixes the issue
> Fix a weird scroll when opening the floor plan screen

- wearApp/src/main/res/values/styles.xml
It now looks like this: 
(following https://developer.android.com/training/wearables/apps/splash-screen)
> Wear app: better splash screen

- androidApp/src/main/java/fr/paug/androidmakers/MainActivity.kt
- gradle/libs.versions.toml
- shared/data/build.gradle.kts
- shared/data/src/androidMain/kotlin/fr/androidmakers/store/graphql/ApolloClientBuilder.android.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/firebase/FirebaseUserRepository.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/firebase/mappers.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/model/User.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/repo/UserRepository.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/common/navigation/UserViewModel.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/signin/GoogleSignInViewModel.kt
Do not cache the `idToken` in RAM. Calling `getIdToken` instead gives a chance to Firebase auth to refresh the token if needed
> Always call firebase getIdToken()

- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/about/AboutScreen.kt
> Fix incorrect ripple on About section

- androidApp/src/main/java/fr/paug/androidmakers/MainActivity.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/ApolloExtensions.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/PartnersGraphQLRepository.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/RoomsGraphQLRepository.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/SessionsGraphQLRepository.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/SpeakersGraphQLRepository.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/VenueGraphQLRepository.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/common/navigation/UserViewModel.kt
Add a dedicated `cacheAndNetwork()` that only emits `Failure` if both cache and network fail or else ignores the error.
Also: merge bookmarks on signin.
> Make the app work offline

- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/common/navigation/AVALayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerDetailsScreen.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerListScreen.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/theme/Typo.kt
Closes #224, #277 and partly #278
> Improved display for small screens

- shared/domain/src/iosMain/kotlin/fr/androidmakers/domain/utils/UrlOpener.ios.kt
I had something "__NSXPCCONNECTION_IS_WAITING_FOR_A_SYNCHRONOUS_REPLY__" in the stacktrace. Not sure what this means but with a completion handler I can't reproduce anymore 🤷 
Closes #269
> Call openUrl with a completionCallback, seems to fix a freeze

- wearApp/build.gradle.kts
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/main/MainViewModel.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/signin/GoogleSignInViewModel.kt
https://github.com/paug/AndroidMakersApp/pull/264 assumed `FirebaseUser` was a KMP one and crashed if not.
> Unbreak wearos signin

- shared/data/build.gradle.kts
- shared/data/src/androidMain/kotlin/fr/androidmakers/store/wear/WearMessagingImpl.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/wear/WearMessaging.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/wear/WearMessagingRepository.kt
- shared/data/src/iosMain/kotlin/fr/androidmakers/store/wear/WearMessagingImpl.kt
- shared/di/src/androidMain/kotlin/fr/androidmakers/di/DataModule.android.kt
- shared/di/src/commonMain/kotlin/fr/androidmakers/di/DataModule.kt
- shared/di/src/commonMain/kotlin/fr/androidmakers/di/DomainModule.kt
- shared/di/src/iosMain/kotlin/fr/androidmakers/di/DataModule.ios.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/interactor/SetSessionBookmarkUseCase.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/repo/MessagingRepository.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/main/MainViewModel.kt
Send a signal to the watch to sync bookmarks.
https://github.com/paug/AndroidMakersApp/assets/372852/31620afb-4b03-4651-9a60-188b569115bd
> Send a signal to the watch to sync bookmarks

- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaColumn.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaRow.kt
<h1>PR description</h1>
When sessions would combine both service and non-service ones, the Card shape would not be applied correctly
<h1>Associated issues</h1>
Fixes #307 
<h1>Screenshots</h1>
> :lipstick: Fix UI bug for sessions

- androidApp/build.gradle.kts
- androidApp/src/main/java/fr/paug/androidmakers/MainActivity.kt
- gradle/libs.versions.toml
`GoogleSignIn` from **play-services-auth** is deprecated. This replaces it with the `CredentialManager` API from the [Jetpack Credentials](https://developer.android.com/jetpack/androidx/releases/credentials) library configured with GoogleId to retrieve the Google Id token supplied to Firebase.
The entire sign-in (and sign-out) process runs inside a single coroutine. There is no need to switch to another dispatcher because all the code is asynchronous and main-safe.
A different sign-in dialog is shown to the user but the functionality remains the same.
**Note**: the Wear app keeps using `GoogleSignIn` because no alternative exists for Wear yet and the Horologist authentication UI is based on `GoogleSignIn`.
> Use CredentialManager for Google Sign-In

- gradle/libs.versions.toml
- shared/domain/src/androidMain/kotlin/fr/androidmakers/domain/utils/DateUtils.android.kt
The current Android code uses the legacy `java.text.SimpleDateFormat` class and creates a new instance of it for every formatting. This also requires unnecessary conversion of the date or time to the legacy `Date` first.
This pull request uses the new thread-safe `DateTimeFormatter` to format `LocalDate` and `LocalTime`, the classes used internally by the kotlinx datetime types. Unwrapping the internal value is a free operation.
In addition, cache the `DateTimeFormatter` for the current `Locale` using a thread-safe custom memoization function. The cache will be invalidated when the default locale changes so the dates will always be localized properly.
Note that `DateTimeFormatter` and other `java.time` APIs are available before API 26 thanks to core library desugaring being enabled in the …
> Optimize Android date and time formatting

- androidApp/src/main/java/fr/paug/androidmakers/MainActivity.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/MainLayout.kt
- The Activity reads `intent.data` after being re-created which causes the initial deep link to be launched again, even after the user navigates away to another screen or if another deep link has been received in the meantime. To avoid this, return `null` as deep link when `savedInstanceState` is non-null after re-creation.
- `addOnNewIntentListener()` is called during each recomposition but the listener is never unregistered which can cause a leak and multiple navigator calls. To avoid this and make the code cleaner, use the `produceState()` function to encapsulate all `deeplink` state logic and unregister the listener in `awaitDispose {}`.
- Catch `IllegalStateException` thrown by `Navigator.navigate(url)` when the url doesn't match any route.
> Ensure Android deep links are only launched once and don't make the app crash

- .github/workflows/pr.yml
- README.md
- build-logic/convention/build.gradle.kts
- build-logic/convention/src/main/kotlin/fr/androidmakers/plugin/AndroidApplicationPlugin.kt
- build-logic/convention/src/main/kotlin/fr/androidmakers/plugin/MultiplatformLibraryPlugin.kt
- wearApp/build.gradle.kts
- Use target JDK 17 in all modules instead of a mix of versions
- Disable Gradle toolchain, use target JDK instead. Toolchains prevent from using more recent JDK versions to build the project
- Upgrade Github actions script to use JDK 21 to build the project and enable Gradle caching. The cache is written during the build that occurs after a branch has been merged in main
- Run the CI when the main branch is updated in addition to pull requests
- Disable the `:shared:linkDebugFrameworkIosArm64` task on the CI: it has no effect since the CI is configured to run on Ubuntu (Mac OS runners should only be used to create release builds anyway)
- Add CI badge in README.
> chore: set the target JDK to 17 and upgrade CI script to build the project with JDK 21

- .github/workflows/pr.yml
Sorry I forgot to fix this when enabling the CI on the main branch.
`github.head_ref` is only valid when the CI is triggered from a PR.
> fix: use the correct group reference when the CI is triggered during a push on the main branch

- androidApp/build.gradle.kts
- gradle/libs.versions.toml
- wearApp/build.gradle.kts
- The Android app will use the same Compose and Lifecycle (and soon Navigation) dependencies as the modules shared with iOS
- Non-JetBrains dependencies are used by the Wear OS app
- Fix incorrect Compose UI tooling dependency in the Wear OS app.
> chore: use JetBrains dependencies in the Android app to avoid conflicts with the shared modules

- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/about/AboutViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaLayoutViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaPagerViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/common/LceViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerDetailViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerListViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/sponsors/SponsorsViewModel.kt
Also change the StateFlows sharing strategy to `SharingStarted.Eagerly` for all ViewModels because:
- All Flows loading data end immediately after emitting the result, so it's OK to keep subscribing to the StateFlow because it becomes "cold"
- Subscribers are currently not lifecycle-aware so the StateFlow always has subscribers, even when the screen is invisible.
> refactor: optimize the usage of Lce in ViewModels

- androidApp/build.gradle.kts
- androidApp/src/test/java/fr/paug/androidmakers/ui/components/AgendaLayoutViewModelTest.kt
- gradle/libs.versions.toml
- shared/build.gradle.kts
- shared/di/build.gradle.kts
- shared/ui/build.gradle.kts
- shared/ui/src/androidMain/kotlin/com/androidmakers/ui/MainLayout.android.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/MainLayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/about/AboutScreen.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/about/AboutViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaLayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaLayoutViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaPager.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaPagerViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/SessionDetailViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/common/LceViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/common/navigation/AVALayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerDetailViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerListViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/sponsors/SponsorScreen.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/theme/AndroidMakersTheme.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/venue/VenuePager.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/venue/VenueViewModel.kt
- shared/ui/src/iosMain/kotlin/com/androidmakers/ui/MainLayout.ios.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/signin/SignInScreen.kt
Also change the behavior of the main bottom navigation:
- Navigating back switches back to the first bottom navigation destination instead of leaving the app
- The state of each main bottom navigation destination is saved and restored when switching between destinations (it's not saved when navigating back).
> refactor: migrate from PreCompose to JetBrains ViewModel and Navigation

- androidApp/src/test/java/fr/paug/androidmakers/fixtures/FakeAndroidMakersStore.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/ApolloExtensions.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/PartnersGraphQLRepository.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/RoomsGraphQLRepository.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/SessionsGraphQLRepository.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/SpeakersGraphQLRepository.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/VenueGraphQLRepository.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/interactor/GetAgendaUseCase.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/repo/RoomsRepository.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/repo/SessionsRepository.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/repo/SpeakersRepository.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaLayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaLayoutViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaPagerViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/common/LceViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerListViewModel.kt
- wearApp/src/main/java/fr/paug/androidmakers/wear/ui/main/MainViewModel.kt
Add a `refresh` boolean argument to use cases to allow changing the cache policy during refresh and attempt to load from network first instead of cache first.
Currently the refresh indicator is hidden when the cache response arrives before the network response which is not accurate because the refresh is still in progress.
This change allows the refresh indicator to be accurate and only hide after the network query completes (with success or error). In case of error, the cache response will be pushed instead if available.
> refactor: change cache policy during manual refresh

- androidApp/src/test/java/fr/paug/androidmakers/fixtures/FakeAndroidMakersStore.kt
- shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/SpeakersGraphQLRepository.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/repo/SpeakersRepository.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/SessionDetailLayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/SessionDetailViewModel.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/model/Lce.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/model/SessionDetailState.kt
- Load all data from a single main Flow instead of collecting the same source Flow multiple times to load the different parts of the session
- Cache the results in a `StateFlow`
- Query `SpeakersRepository` once per session to load all speakers at once.
> refactor: optimize loading in SessionDetailViewModel

- androidApp/src/main/res/values-night/themes.xml
- androidApp/src/main/res/values/themes.xml
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaLayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/SessionDetailLayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/common/LceLayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/common/navigation/AVALayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerDetailsScreen.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerListScreen.kt
- Make the Android app theme blend smoothly from the "splash" screen to the content
- Consume Window insets early in `AVALayout` so they don't have to be overridden in child layouts
- Change the app bar color during scroll in detail screens.
> refactor: improve Edge-to-edge implementation

- shared/di/src/androidMain/kotlin/fr/androidmakers/di/DomainModule.android.kt
- shared/di/src/androidMain/kotlin/fr/androidmakers/di/Inject.android.kt
- shared/di/src/commonMain/kotlin/fr/androidmakers/di/Inject.kt
- shared/di/src/iosMain/kotlin/fr/androidmakers/di/DomainModule.ios.kt
- shared/di/src/iosMain/kotlin/fr/androidmakers/di/Inject.ios.kt
- shared/domain/src/androidMain/kotlin/fr/androidmakers/domain/interactor/OpenMapUseCase.android.kt
- shared/domain/src/androidMain/kotlin/fr/androidmakers/domain/interactor/ShareSessionUseCase.android.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/interactor/OpenMapUseCase.kt
- shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/interactor/ShareSessionUseCase.kt
- shared/domain/src/iosMain/kotlin/fr/androidmakers/domain/interactor/OpenMapUseCase.ios.kt
- shared/domain/src/iosMain/kotlin/fr/androidmakers/domain/interactor/ShareSessionUseCase.ios.kt
Expect/Actual classes are in Beta and should be avoided whenever possible, as recommended in the [official Kotlin documentation](https://kotlinlang.org/docs/multiplatform-expect-actual.html#expected-and-actual-classes).
Use interfaces in place of expect classes, or nothing if the class is not referenced from common code.
> refactor: remove unnecessary expect/actual classes

- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/SessionDetailLayout.kt
- shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerDetailsScreen.kt
Having some of the session and speaker attributes selectable could be useful. For example, I was writing a summary document about the conference, using my phone, and it would have been easier if I could have copied/pasted this information into my document.
So:
Make the following text items selectable:
* Session details:
- Session title
- Session description
- Speaker name
- Speaker bio
* Speaker details:
- Speaker name
- Speaker bio
|Screen|Screenshots (Android 35 emulator)|
|---|---|
|Session details<br>(session section)|<img src="https://github.com/user-attachments/assets/3618540e-9ea4-44fd-8144-e1868a84cdc1" width="240"> <img src="https://github.com/user-attachments/assets/b2f0b5a6-20be-4d0f-b432-689a3c83fef6" width="240">|
|Session details<br>(speaker section)|<img …
> Make some text items selectable.
