app/src/main/AndroidManifest.xml
app/src/main/java/fr/paug/androidmakers/ui/fragment/AboutFragment.java
app/src/main/java/fr/paug/androidmakers/util/WifiUtil.java
app/src/main/res/drawable/ic_network_wifi_black_24dp.xml
app/src/main/res/layout/fragment_about.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

Added a button near the venue's wifi information to
automatically configure the wifi network of the venue
and connect to it.

[DEV] Added a way to automatically configure the wifi

---

app/src/main/java/fr/paug/androidmakers/util/CustomTabUtil.java
app/src/main/java/fr/paug/androidmakers/util/MapUtil.java
app/src/main/java/fr/paug/androidmakers/util/SessionSelector.java
app/src/main/java/fr/paug/androidmakers/util/WifiUtil.java

Because I prefer things to be clear & clean

Make utility classes non-instantiable & non-extensible

---

app/src/main/java/fr/paug/androidmakers/manager/AgendaRepository.java
app/src/main/java/fr/paug/androidmakers/ui/adapter/AgendaPagerAdapter.java
app/src/main/java/fr/paug/androidmakers/ui/adapter/ScheduleDayAdapter.java
app/src/main/java/fr/paug/androidmakers/ui/adapter/ScheduleSession.java
app/src/main/java/fr/paug/androidmakers/ui/fragment/AgendaFragment.java
app/src/main/java/fr/paug/androidmakers/ui/util/SessionFilter.java
app/src/main/java/fr/paug/androidmakers/util/EmojiUtils.java
app/src/main/res/drawable/ic_filter_list_white_24dp.xml
app/src/main/res/layout/filter_header.xml
app/src/main/res/layout/filter_item.xml
app/src/main/res/layout/fragment_agenda.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml
build.gradle

This PR adds bookmark/language/room filters accessible from a DrawerLayout

Add filters

---

build.gradle

The Google repository was imported twice

Fixed maven repos

---

app/build.gradle

Remove duplicated multidex declaration

---

app/build.gradle.kts
app/src/main/java/fr/paug/androidmakers/AndroidMakersApplication.kt
app/src/main/java/fr/paug/androidmakers/manager/AndroidMakersStore.kt
app/src/main/java/fr/paug/androidmakers/ui/activity/SessionDetailActivity.kt
app/src/main/java/fr/paug/androidmakers/ui/fragment/AgendaFragment.kt
app/src/main/res/layout/activity_detail.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

- do not allow feedback until the session starts
- add localization 
- filter out coffe breaks/empty talks

Openfeedback improvements

---

.github/workflows/pr.yml

This is a simple CI script that makes sure the app compiles

Add a "PR" workflow in Github actions

---

app/src/main/java/fr/paug/androidmakers/AndroidMakersApplication.kt
app/src/main/java/fr/paug/androidmakers/ui/activity/MainActivity.kt
app/src/main/java/fr/paug/androidmakers/ui/components/AVALayout.kt
app/src/main/java/fr/paug/androidmakers/ui/components/AboutLayout.kt
app/src/main/java/fr/paug/androidmakers/ui/components/AgendaColumn.kt
app/src/main/java/fr/paug/androidmakers/ui/components/AgendaRow.kt
app/src/main/java/fr/paug/androidmakers/ui/components/Separators.kt
app/src/main/java/fr/paug/androidmakers/ui/components/SessionDetailLayout.kt
app/src/main/java/fr/paug/androidmakers/ui/components/VenueLayout.kt
app/src/main/java/fr/paug/androidmakers/ui/theme/AndroidMakersTheme.kt
app/src/main/java/fr/paug/androidmakers/ui/util/Images.kt
build-logic/src/main/kotlin/fr/androidmakers/gradle/android/application/AndroidApplicationPlugin.kt

Add dark mode
Closes https://github.com/paug/AndroidMakersApp/issues/65

🌙 Add dark mode

---

app/src/main/java/fr/paug/androidmakers/ui/viewmodel/LceViewModel.kt

Fixes https://github.com/paug/AndroidMakersApp/issues/108

Do not emit Loading when refreshing

---

app/src/main/java/fr/paug/androidmakers/ui/components/SessionDetailLayout.kt
app/src/main/java/fr/paug/androidmakers/util/TimeUtils.kt

Closes https://github.com/paug/AndroidMakersApp/issues/110

Use Paris timezone for dates

---

.gitignore
.idea/icon.svg

Add AndroidStudio icon

---

app/src/main/java/fr/paug/androidmakers/ui/components/agenda/AgendaLayout.kt
app/src/main/java/fr/paug/androidmakers/ui/components/agenda/AgendaPager.kt
app/src/main/java/fr/paug/androidmakers/util/TimeUtils.kt

Check in starts at 8am, not 10am

Fix the time zone of sessions

---

app/src/main/java/fr/paug/androidmakers/ui/components/speakers/SpeakerScreen.kt

Set a background to searchbar to hide speakers behind it

---

app/src/main/res/values/strings.xml

New twitter hashtag

---

app/src/main/res/values/strings.xml

I forgot to change also the text in the Twitter query

The twitter tag linked is now fixed

---

app/src/main/java/fr/paug/androidmakers/ui/MainActivity.kt
app/src/main/java/fr/paug/androidmakers/ui/components/AVALayout.kt
app/src/main/java/fr/paug/androidmakers/ui/components/about/AboutLayout.kt
app/src/main/java/fr/paug/androidmakers/ui/components/session/SessionDetailLayout.kt
app/src/main/res/drawable/ic_network_x.xml
app/src/main/res/values/strings.xml

I have just updated the references to Twitter in the app.
Closes #175

Changed the Twitter references

---

androidApp/build.gradle.kts
androidApp/src/main/java/fr/paug/androidmakers/AndroidMakersApplication.kt
androidApp/src/main/java/fr/paug/androidmakers/ui/MainActivity.kt
androidApp/src/main/java/fr/paug/androidmakers/ui/components/AVALayout.kt
androidApp/src/main/java/fr/paug/androidmakers/ui/components/MainLayout.kt
androidApp/src/main/java/fr/paug/androidmakers/ui/components/SigninButton.kt
gradle/libs.versions.toml
shared/data/build.gradle.kts
shared/data/src/commonMain/kotlin/fr/androidmakers/store/firebase/FirebaseUserRepository.kt
shared/data/src/commonMain/kotlin/fr/androidmakers/store/firebase/mappers.kt
shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/model/User.kt
shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/repo/UserRepository.kt

Basic move from Firebase Auth on Android to firebase KMP (unofficial, for the moment)

Moved Google Firebase Auth to KMP

---

androidApp/src/main/java/fr/paug/androidmakers/AndroidMakersApplication.kt
androidApp/src/main/java/fr/paug/androidmakers/ui/MainActivity.kt
androidApp/src/main/java/fr/paug/androidmakers/ui/theme/AndroidMakersTheme.kt
androidApp/src/main/res/values/strings.xml
iosApp/RobotConf/Model/Model.swift
iosApp/RobotConf/UI/About/AboutViewModel.swift
shared/domain/src/androidMain/kotlin/fr/androidmakers/domain/utils/UrlOpener.android.kt
shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/interactor/OpenCocUseCase.kt
shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/interactor/OpenFaqUseCase.kt
shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/interactor/OpenXAccountUseCase.kt
shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/interactor/OpenXHashtagUseCase.kt
shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/interactor/OpenYoutubeUseCase.kt
shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/utils/Constants.kt
shared/domain/src/commonMain/kotlin/fr/androidmakers/domain/utils/UrlOpener.kt
shared/domain/src/iosMain/kotlin/fr/androidmakers/domain/utils/UrlOpener.ios.kt

To easily open Urls on both systems, I added a tool in the common code.
There is room for improvement 😄

Added a Url Opener Helper

---

gradle/libs.versions.toml
wearApp/build.gradle.kts
wearApp/src/main/java/fr/paug/androidmakers/wear/data/LocalPreferencesRepository.kt
wearApp/src/main/java/fr/paug/androidmakers/wear/ui/main/MainActivity.kt
wearApp/src/main/java/fr/paug/androidmakers/wear/ui/main/MainViewModel.kt
wearApp/src/main/java/fr/paug/androidmakers/wear/ui/session/list/SessionListScreen.kt
wearApp/src/main/java/fr/paug/androidmakers/wear/ui/settings/SettingsScreen.kt
wearApp/src/main/java/fr/paug/androidmakers/wear/ui/settings/SettingsViewModel.kt
wearApp/src/main/java/fr/paug/androidmakers/wear/ui/theme/Color.kt
wearApp/src/main/res/values-fr/strings.xml
wearApp/src/main/res/values/strings.xml

Just a few tweaks
- tried to use the same colors as the phone app
- the clock on top moves away when scrolling
- use DataStore for shared prefs
[tweaks.webm](https://github.com/paug/AndroidMakersApp/assets/372852/1cfff9ab-f7df-47bb-a6b7-af67e514508d)

Wear app: Tweak colors and design a little bit

---

shared/data/src/commonMain/graphql/operations.graphql
shared/data/src/commonMain/kotlin/fr/androidmakers/store/graphql/mappers.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaLayout.kt

Prevents service items to be clicked (and have openfeedback, etc...)

Add back isSessionService

---

shared/ui/src/commonMain/kotlin/com/androidmakers/ui/MainLayout.kt
shared/ui/src/iosMain/kotlin/com/androidmakers/ui/MainLayoutViewController.kt

https://github.com/paug/AndroidMakersApp/assets/8111500/17bc0977-78a5-4f5c-aa7c-e66ef242f1a2

Enable the back gesture on iOS

---

wearApp/src/main/java/fr/paug/androidmakers/wear/ui/main/MainActivity.kt
wearApp/src/main/java/fr/paug/androidmakers/wear/ui/main/MainViewModel.kt
wearApp/src/main/java/fr/paug/androidmakers/wear/ui/settings/SettingsScreen.kt
wearApp/src/main/res/values-fr/strings.xml
wearApp/src/main/res/values/strings.xml

Handy when bookmarking on mobile, clicking the button will sync.

Wear app: Add a refresh button

---

shared/ui/src/androidMain/kotlin/com/androidmakers/ui/common/SigninButton.android.kt
shared/ui/src/iosMain/kotlin/com/androidmakers/ui/MainLayoutViewController.kt
shared/ui/src/iosMain/kotlin/com/androidmakers/ui/common/SigninButton.ios.kt

Removed the Sign In Button for iOS

Disabled iOS Sign In

---

gradle/libs.versions.toml

There was a UI glitch on Wear (text was randomly too bright on certain elements), turns out updating dependencies fixes the glitch.
Tested both apps quickly, all seems to work correctly at first glance.

Update a bunch of dependencies

---

androidApp/src/main/AndroidManifest.xml
androidApp/src/main/java/fr/paug/androidmakers/MainActivity.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/MainLayout.kt

```
adb shell am start -W -a android.intent.action.VIEW -d "https://androidmakers.fr/speaker/a82de654-53d7-4c16-989a-5efddf36983e"
adb shell am start -W -a android.intent.action.VIEW -d "https://androidmakers.fr/session/625798"
```

Deeplinks management on Android

---

shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaColumn.kt

fix(272) Fix Alignment when the list is not full

---

shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaColumn.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaRow.kt

fix(267) Fix the weird ripple on Agenda

---

shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/AgendaRow.kt

Hide room & language for service sessions

---

shared/data/src/commonMain/kotlin/fr/androidmakers/store/firebase/FirebaseUserRepository.kt

Robustify getIdToken

---

androidApp/src/main/java/fr/paug/androidmakers/AndroidMakersApplication.kt
gradle/libs.versions.toml
iosApp/AndroidMakers/AppDelegate.swift
shared/build.gradle.kts
shared/ui/build.gradle.kts
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/SessionDetailLayout.kt

Initialize openfeedback globally with the appcontext instead of activity context.
See https://github.com/paug/openfeedback-sdk-kotlin/pull/28

Update openfeedback sdk

---

androidApp/proguard-rules.pro
gradle/libs.versions.toml
shared/ui/build.gradle.kts
shared/ui/src/androidMain/kotlin/com/androidmakers/ui/common/SigninButton.android.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/MainLayout.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/about/AboutScreen.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/agenda/SessionDetailLayout.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/common/LceLayout.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerDetailsScreen.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/speakers/SpeakerListScreen.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/sponsors/SponsorScreen.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/venue/FloorPlan.kt
shared/ui/src/commonMain/kotlin/com/androidmakers/ui/venue/VenueScreen.kt
wearApp/src/main/java/fr/paug/androidmakers/wear/ui/session/details/SessionDetailScreen.kt

Currently an older version is used because newer versions depend on Compose 1.7

feat: replace qdsfdhvh-imageloader library with Coil 3

---

androidApp/src/main/AndroidManifest.xml

Supported automatically since JetBrains/Androidx Navigation 2.8

feat: enable predictive back animations on Android
